"""initial schema

Revision ID: 4e3473d74d99
Revises: 
Create Date: 2026-01-04 12:24:11.005880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3473d74d99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_parcel_matches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('route_id', sa.BigInteger(), nullable=False),
    sa.Column('parcel_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), server_default='proposed', nullable=False),
    sa.Column('delta_distance_m', sa.Float(), nullable=False),
    sa.Column('delta_duration_s', sa.Float(), nullable=False),
    sa.Column('base_distance_m', sa.Float(), nullable=True),
    sa.Column('base_duration_s', sa.Float(), nullable=True),
    sa.Column('new_distance_m', sa.Float(), nullable=True),
    sa.Column('new_duration_s', sa.Float(), nullable=True),
    sa.Column('algorithm_version', sa.Text(), server_default='mvp-0.1', nullable=False),
    sa.Column('debug', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('proposed','accepted','rejected','expired')", name='chk_route_parcel_match_status'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('parcels', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('parcels', sa.Column('pickup_after', sa.DateTime(timezone=True), nullable=True))
    op.add_column('parcels', sa.Column('pickup_before', sa.DateTime(timezone=True), nullable=True))
    op.add_column('parcels', sa.Column('dropoff_after', sa.DateTime(timezone=True), nullable=True))
    op.add_column('parcels', sa.Column('dropoff_before', sa.DateTime(timezone=True), nullable=True))
    op.add_column('parcels', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('parcels', sa.Column('size_class', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcels', 'size_class')
    op.drop_column('parcels', 'weight_kg')
    op.drop_column('parcels', 'dropoff_before')
    op.drop_column('parcels', 'dropoff_after')
    op.drop_column('parcels', 'pickup_before')
    op.drop_column('parcels', 'pickup_after')
    op.drop_column('parcels', 'title')
    op.drop_table('route_parcel_matches')
    # ### end Alembic commands ###
